### ISSUE TITLE
SpringChatClientTest is unstable

### ISSUE THREAD

**Issue by kaikreuzer** [lmos-ai/arc#15]
The test `SpringChatClientTest > test chat completion text()` seems to randomly fail, see [this PR build](https://github.com/lmos-ai/arc/actions/runs/10317816256/job/28562863662?pr=14), which did not change any code:

```
1 test completed, 1 failed
> Task :arc-spring-ai:test FAILED

SpringChatClientTest > test chat completion text() FAILED
    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:180
        Caused by: org.springframework.beans.factory.BeanCreationException at ConstructorResolver.java:648
            Caused by: org.springframework.beans.BeanInstantiationException at SimpleInstantiationStrategy.java:177
                Caused by: java.lang.NoSuchFieldError at DefaultErrorWebExceptionHandler.java:94
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2024-08-09T10:37:58.169Z  INFO 2412 --- [localhost:32769] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:32769

com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:249) ~[mongodb-driver-core-4.11.2.jar:na]
	at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:235) ~[mongodb-driver-core-4.11.2.jar:na]
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishRead(UnixAsynchronousSocketChannelImpl.java:447) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:195) ~[na:na]
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217) ~[na:na]
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:[306](https://github.com/lmos-ai/arc/actions/runs/10317816256/job/28562863662?pr=14#step:5:307)) ~[na:na]
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]



FAILURE: Build failed with an exception.
```

**Comment by patwlan** [comment]
We will be dropping support for SpringAI and use LangChain4j.

**Comment by patwlan** [comment]
Yes, we have dropped support for Spring AI for now and will focus on LangChain4j first.
