### ISSUE TITLE
arc-runner failing to run

### ISSUE THREAD

**Issue by maxandersen** [lmos-ai/arc#53]
first kudos for using jbang to make this easy to try - great usecase for it :)

I ran the following:

```
curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force https://github.com/lmos-ai/arc/blob/main/arc-runner/arc.java
arc install weather
export ARC_AI_KEY=sk-SECRET
export ARC_CLIENT=openai
export ARC_MODEL=gtp-4o
arc run
```

which then resulted in:

```
 arc run
Staring Arc Runner...
2024-12-03T11:08:42.001+01:00  INFO 47399 --- [           main] a.a.l.a.s.agents.ScriptingAgentLoader    : Discovered the following agents (scripting): weather-agent
2024-12-03T11:08:42.006+01:00 DEBUG 47399 --- [           main] a.a.l.a.a.events.LoggingEventHandler     : Event published: AgentLoadedEvent(name=weather.agent.kts, errorMessage=null)
2024-12-03T11:08:42.690+01:00  WARN 47399 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.2024-12-03T11:08:42.690+01:00  WARN 47399 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.2024-12-03T11:08:42.690+01:00  WARN 47399 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.2024-12-03T11:08:42.690+01:00  WARN 47399 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.2024-12-03T11:08:42.714+01:00 ERROR 47399 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatCompleterProvider' defined in class path resource [ai/ancf/lmos/arc/spring/ClientsConfiguration.classorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatCompleterProvider' defined in class path resource [ai/ancf/lmos/arc/spring/ClientsConfiguration.classorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatCompleterProvider' defined in class path resource [ai/ancf/lmos/arc/spring/ClientsConfiguration.class	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.12.jar:6.1	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.12.jar:6.1	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971) ~[spring-context-6.1.12.jar:6.1.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.12.jar:6.1.12]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.3.jar:3.3.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.3.jar:3.3.3]
	at ai.ancf.lmos.arc.runner.RunArc.run(Run.kt:73) ~[arc-runner-0.112.0.jar:na]
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine.access$1500(CommandLine.java:148) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421) ~[picocli-4.7.6.jar:4.7.6]
	at picocli.CommandLine.execute(CommandLine.java:2174) ~[picocli-4.7.6.jar:4.7.6]
	at arc.runner.arc.main(arc.java:24) ~[arc.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ai.ancf.lmos.arc.agents.llm.ChatCompleterProvider]: Factory method 'chatCompleterProvider' threw exceptioCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ai.ancf.lmos.arc.agents.llm.ChatCompleterProvider]: Factory method 'chatCompleterProvider' threw exceptio	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.12.jar:6.1.12]
	... 26 common frames omitted
Caused by: java.util.ServiceConfigurationError: com.azure.core.util.tracing.Tracer: Provider com.azure.core.tracing.opentelemetry.OpenTelemetryTracer could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729) ~[na:na]
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403) ~[na:na]
	at com.azure.core.util.tracing.DefaultTracerProvider.createFallbackTracer(DefaultTracerProvider.java:35) ~[azure-core-1.50.0.jar:1.50.0]
	at com.azure.core.util.tracing.DefaultTracerProvider.<clinit>(DefaultTracerProvider.java:25) ~[azure-core-1.50.0.jar:1.50.0]
	at com.azure.core.util.tracing.TracerProvider.getDefaultProvider(TracerProvider.java:43) ~[azure-core-1.50.0.jar:1.50.0]
	at com.azure.core.http.HttpPipelineBuilder.configureTracing(HttpPipelineBuilder.java:99) ~[azure-core-1.50.0.jar:1.50.0]
	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:91) ~[azure-core-1.50.0.jar:1.50.0]
	at com.azure.ai.openai.OpenAIClientBuilder.createHttpPipeline(OpenAIClientBuilder.java:323) ~[azure-ai-openai-1.0.0-beta.7.jar:1.0.0-beta.7]
	at com.azure.ai.openai.OpenAIClientBuilder.buildInnerNonAzureOpenAIClient(OpenAIClientBuilder.java:328) ~[azure-ai-openai-1.0.0-beta.7.jar:1.0.0-beta.7]
	at com.azure.ai.openai.OpenAIClientBuilder.buildAsyncClient(OpenAIClientBuilder.java:340) ~[azure-ai-openai-1.0.0-beta.7.jar:1.0.0-beta.7]
	at ai.ancf.lmos.arc.spring.ClientsConfiguration.openAIAsyncClient$lambda$1(ClientsConfiguration.kt:40) ~[arc-spring-boot-starter-0.112.0.jar:na]
	at ai.ancf.lmos.arc.spring.ClientsConfiguration.chatCompleterProvider(ClientsConfiguration.kt:93) ~[arc-spring-boot-starter-0.112.0.jar:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.12.jar:6.1.12]
	... 27 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/azure/core/util/LibraryTelemetryOptions
	at com.azure.core.tracing.opentelemetry.OpenTelemetryTracer.<init>(OpenTelemetryTracer.java:96) ~[azure-core-tracing-opentelemetry-1.0.0-beta.52.jar:1.0.0-beta.52]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[na:na]
	... 42 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.azure.core.util.LibraryTelemetryOptions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	... 47 common frames omitted

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatCompleterProvider' defined in class path resource [ai/ancf/lmos/arc/spring/ClientsConfiguration.classorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatCompleterProvider' defined in class path resource [ai/ancf/lmos/arc/spring/ClientsConfiguration.classorg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatCompleterProvider' defined in class path resource [ai/ancf/lmos/arc/spring/ClientsConfiguration.class	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:971)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
	at ai.ancf.lmos.arc.runner.RunArc.run(Run.kt:73)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at arc.runner.arc.main(arc.java:24)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ai.ancf.lmos.arc.agents.llm.ChatCompleterProvider]: Factory method 'chatCompleterProvider' threw exceptioCaused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ai.ancf.lmos.arc.agents.llm.ChatCompleterProvider]: Factory method 'chatCompleterProvider' threw exceptio	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
	... 26 more
Caused by: java.util.ServiceConfigurationError: com.azure.core.util.tracing.Tracer: Provider com.azure.core.tracing.opentelemetry.OpenTelemetryTracer could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at com.azure.core.util.tracing.DefaultTracerProvider.createFallbackTracer(DefaultTracerProvider.java:35)
	at com.azure.core.util.tracing.DefaultTracerProvider.<clinit>(DefaultTracerProvider.java:25)
	at com.azure.core.util.tracing.TracerProvider.getDefaultProvider(TracerProvider.java:43)
	at com.azure.core.http.HttpPipelineBuilder.configureTracing(HttpPipelineBuilder.java:99)
	at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:91)
	at com.azure.ai.openai.OpenAIClientBuilder.createHttpPipeline(OpenAIClientBuilder.java:323)
	at com.azure.ai.openai.OpenAIClientBuilder.buildInnerNonAzureOpenAIClient(OpenAIClientBuilder.java:328)
	at com.azure.ai.openai.OpenAIClientBuilder.buildAsyncClient(OpenAIClientBuilder.java:340)
	at ai.ancf.lmos.arc.spring.ClientsConfiguration.openAIAsyncClient$lambda$1(ClientsConfiguration.kt:40)
	at ai.ancf.lmos.arc.spring.ClientsConfiguration.chatCompleterProvider(ClientsConfiguration.kt:93)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
	... 27 more
Caused by: java.lang.NoClassDefFoundError: com/azure/core/util/LibraryTelemetryOptions
	at com.azure.core.tracing.opentelemetry.OpenTelemetryTracer.<init>(OpenTelemetryTracer.java:96)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 42 more
Caused by: java.lang.ClassNotFoundException: com.azure.core.util.LibraryTelemetryOptions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 47 more
```

**Comment by patwlan** [comment]
Welcome! And a big thanks for your feedback!

Yes, we are still getting to grips with jbang. There seems to be a missing dependency after updating to the new Spring version. 

I have revert the version to get it working again.

Please let me know if it works.

I would leave the ticket open until we fix the new version.

**Comment by patwlan** [comment]
There is a typo in the model, should be gpt-4o...

But that has nothing to do with your exception of course

**Comment by patwlan** [comment]
Hi, as it seems to be fixed, i would close this ticket if there are no objections.
